vector<Program *> generateTestPrograms()
{
  return vector<Program *>{
      new Program(1, FacultyType::ComputerScience, City::Ismailia, 1, UniversityType::Public,
                  University::SuezCanalUniversity, 5, coverLetterPriority),
      new Program(2, FacultyType::Science, City::Ismailia, 1, UniversityType::Public, University::SuezCanalUniversity, 5,
                  scienceGradePriority),
      new Program(3, FacultyType::Education, City::Ismailia, 1, UniversityType::Public, University::SuezCanalUniversity,
                  5, arabicGradePriority),
      new Program(4, FacultyType::Engineering, City::Ismailia, 1, UniversityType::Public,
                  University::SuezCanalUniversity, 5, englishGradePriority),
      new Program(5, FacultyType::Medicine, City::Ismailia, 1, UniversityType::Public, University::SuezCanalUniversity,
                  5, mathAndScienceWeightedPriority),
      new Program(6, FacultyType::ComputerScience, City::PortSaid, 5, UniversityType::Public,
                  University::PortSaidUniversity, 5, mathGradePriority),
      new Program(7, FacultyType::Science, City::PortSaid, 5, UniversityType::Public, University::PortSaidUniversity, 5,
                  scienceGradePriority),
      new Program(8, FacultyType::Education, City::PortSaid, 5, UniversityType::Public, University::PortSaidUniversity,
                  5, arabicGradePriority),
      new Program(9, FacultyType::Engineering, City::PortSaid, 5, UniversityType::Public, University::PortSaidUniversity,
                  5, englishGradePriority),
      new Program(10, FacultyType::Medicine, City::PortSaid, 5, UniversityType::Public, University::PortSaidUniversity, 5,
                  mathAndScienceWeightedPriority),
      new Program(11, FacultyType::ComputerScience, City::Cairo, 2, UniversityType::Public, University::CairoUniversity,
                  5, mathGradePriority),
      new Program(12, FacultyType::Science, City::Cairo, 2, UniversityType::Public, University::CairoUniversity, 5,
                  scienceGradePriority),
      new Program(13, FacultyType::Education, City::Cairo, 2, UniversityType::Public, University::CairoUniversity, 5,
                  arabicGradePriority),
      new Program(15, FacultyType::Engineering, City::Cairo, 2, UniversityType::Public, University::CairoUniversity, 5,
                  englishGradePriority),
      new Program(15, FacultyType::Medicine, City::Cairo, 2, UniversityType::Public, University::CairoUniversity, 5,
                  mathAndScienceWeightedPriority)};
}